apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-pgbouncer-exporter.fullname" . }}
  labels:
    {{- include "prometheus-pgbouncer-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-pgbouncer-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-pgbouncer-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --log.level={{ .Values.logLevel }}
            - --log.format={{ .Values.logFormat }}
            - --pgBouncer.connectionString=$(CONNECTION_STRING)
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "prometheus-pgbouncer-exporter.secretName" . }}
                  key: {{ include "prometheus-pgbouncer-exporter.secretKey" . }}
          ports:
            - name: exporter-port
              containerPort: 9127
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: exporter-port
          readinessProbe:
            httpGet:
              path: /
              port: exporter-port
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
