apiVersion: v2
name: prometheus-pgbouncer-exporter
description: Prometheus exporter for pgbouncer metrics
home: https://github.com/prometheus-community/helm-charts
sources:
  - https://github.com/prometheus-community/pgbouncer_exporter

keywords:
  - prometheus
  - pgbouncer

maintainers:
  - name: Pluggi
    email: pluggi512@gmail.com

type: application

version: "1.1.0"

appVersion: "0.4.0"
